name: cartza
description: A simple ecommerce demo app.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.1
  iconsax_plus: ^1.0.0
  google_fonts: ^5.0.0
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.1
  image_picker: ^1.1.1
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
